spring.application.name=user-management
server.port=8888
spring.config.import=optional:configserver:http://localhost:8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#disabled log in console
logging.pattern.console=
#file proprieties
logging.file.path=logging/global.logs
logging.file.name=${logging.file.path}/global.log
logging.logback.rollingpolicy.max-file.size=5MB
logging.logback.rollingpolicy.max-history=5



